version: '3.9'

services:

  appdaf:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: appdaf
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_appdaf
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - appdaf
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_appdaf
    restart: always
    environment:
      POSTGRES_DB: AppDAF
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_appdaf
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fallou@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5052:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge